P11: P11.c
	gcc P11.c -o P11 -Wall -pedantic

P12: P12.c
	gcc P12.c -o P12 -Wall -pedantic

P21: P21.c
	gcc P21.c -o P21 -Wall -pedantic

P22: P22.c
	gcc P22.c -o P22 -Wall -pedantic

P23: P23.c
	gcc P23.c -o P23 -Wall -pedantic

clean:
	rm -rf *.out
